spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scms2_prod?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  thymeleaf:
    cache: true

logging:
  level:
    com.scms: INFO
    org.springframework.web: WARN
